# Generated by Django 6.0.7 on 2026-07-16 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_worker_downloads', models.BooleanField(default=True, help_text='If off, the download action returns 403 for Workers regardless of department.')),
                ('enable_file_preview', models.BooleanField(default=True, help_text='If off, the inline document preview action is disabled for everyone, Department Heads included.')),
                ('show_inactive_by_default', models.BooleanField(default=False, help_text='Whether Department Heads see inactive documents by default in list views. Always overridable per-request with ?show_inactive=true|false. Never applies to Workers, who never see inactive documents regardless.')),
                ('enable_document_versioning', models.BooleanField(default=True, help_text="If on, replacing a document's file via the 'replace' action auto-increments its version number instead of keeping the version string unchanged.")),
                ('default_page_size', models.PositiveSmallIntegerField(default=20, help_text="Default items-per-page for list endpoints when the client doesn't pass ?page_size=.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
