# Generated by Django 6.0.7 on 2026-07-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('XLSX', 'Excel')], max_length=10),
        ),
    ]
