# Generated by Django 6.0.7 on 2026-07-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_document_multi_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency'), ('SAFETY', 'Safety'), ('ANNOUNCEMENT', 'Announcement'), ('MAINTENANCE', 'Maintenance'), ('LEAVE_REQUEST', 'Leave Request'), ('SYSTEM', 'System'), ('GENERAL', 'General')], db_index=True, max_length=20),
        ),
    ]
