# Generated by Django 6.0.7 on 2026-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_docs',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this worker can upload and manage documents pending Head approval.'),
        ),
    ]
