# Generated by Django 6.0.7 on 2026-07-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_can_manage_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DEPARTMENT_HEAD', 'Department Head'), ('WORKER', 'Worker')], db_index=True, default='WORKER', max_length=20),
        ),
    ]
