# Generated by Django 6.0.7 on 2026-07-29 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_daily_limit_override',
            field=models.PositiveIntegerField(blank=True, help_text='Per-user override for the daily AI chat message limit. Null falls back to the role-based default (Admin=200, Department Head=100, Worker=30). Settable only by an Admin.', null=True),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('SAFETY', 'Safety'), ('ANNOUNCEMENT', 'Announcement'), ('MAINTENANCE', 'Maintenance'), ('LEAVE_REQUEST', 'Leave Request'), ('SYSTEM', 'System'), ('GENERAL', 'General')], default='ANNOUNCEMENT', help_text='Maps to Alert.type when this template is used to send an actual notification.', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
                'ordering': ['-updated_at'],
            },
        ),
    ]
